CREATE TABLE IF NOT EXISTS USER (
    UUID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    UID CHAR(40) NOT NULL UNIQUE, 
    PASSWORD CHAR(40) NOT NULL,
    NAME CHAR(40) NOT NULL);

INSERT OR IGNORE INTO USER values (1, 'timeline', 'timeline', 'timeUser');